config/routes.rb
Rails.application.routes.draw do
  resources :vocabularies

  get 'home/index'

  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  root to: "home#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vocabulary.rb
class Vocabulary < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Localization
end

app/controllers/concerns/localization.rb
# frozen_string_literal: true

module Localization
  extend ActiveSupport::Concern

  included do
    around_action :switch_locale

    protected

    def switch_locale(&action)
      locale = extract_locale_from_param || I18n.default_locale

      I18n.with_locale(locale, &action)
    end

    def extract_locale_from_param
      return params[:locale] if I18n.locale_available?(params[:locale])

      nil
    end

    private

    def default_url_options
      { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/vocabularies_controller.rb
class VocabulariesController < ApplicationController
  before_action :set_vocabulary, only: %i[ show edit update destroy ]

  # GET /vocabularies
  def index
    @vocabularies = Vocabulary.all
  end

  # GET /vocabularies/1
  def show
  end

  # GET /vocabularies/new
  def new
    @vocabulary = Vocabulary.new
  end

  # GET /vocabularies/1/edit
  def edit
  end

  # POST /vocabularies
  def create
    @vocabulary = Vocabulary.new(vocabulary_params)

    if @vocabulary.save
      redirect_to @vocabulary, notice: "Vocabulary was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /vocabularies/1
  def update
    if @vocabulary.update(vocabulary_params)
      redirect_to @vocabulary, notice: "Vocabulary was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /vocabularies/1
  def destroy
    @vocabulary.destroy!
    redirect_to vocabularies_url, notice: "Vocabulary was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vocabulary
      @vocabulary = Vocabulary.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vocabulary_params
      params.require(:vocabulary).permit(:word, :translation, :context, :user_id)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/vocabularies_helper.rb
module VocabulariesHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Vocab</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <!-- <a class="nav-link" href="#">Home</a> -->
      </li>
    </ul>

    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Vocabularies', vocabularies_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='<%= I18n.locale %>'>
  <head>
    <title>Vocab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/nav' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/vocabularies/_form.html.erb
<%= form_with(model: vocabulary) do |form| %>
  <% if vocabulary.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vocabulary.errors.count, "error") %> prohibited this vocabulary from being saved:</h2>

      <ul>
        <% vocabulary.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :word, style: "display: block" %>
    <%= form.text_field :word %>
  </div>

  <div>
    <%= form.label :translation, style: "display: block" %>
    <%= form.text_area :translation %>
  </div>

  <div>
    <%= form.label :context, style: "display: block" %>
    <%= form.text_area :context %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/vocabularies/_vocabulary.html.erb
<div id="<%= dom_id vocabulary %>">
  <p>
    <strong>Word:</strong>
    <%= vocabulary.word %>
  </p>

  <p>
    <strong>Translation:</strong>
    <%= vocabulary.translation %>
  </p>

  <p>
    <strong>Context:</strong>
    <%= vocabulary.context %>
  </p>

  <p>
    <strong>User:</strong>
    <%= vocabulary.user_id %>
  </p>

</div>

app/views/vocabularies/edit.html.erb
<h1>Editing vocabulary</h1>

<%= render "form", vocabulary: @vocabulary %>

<br>

<div>
  <%= link_to "Show this vocabulary", @vocabulary %> |
  <%= link_to "Back to vocabularies", vocabularies_path %>
</div>

app/views/vocabularies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Vocabularies</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Word</th>
      <th scope="col">Explanation</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% if @vocabularies.blank? %>
      <tr>
        <td colspan="2">
          No vocabulary yet, please <%= link_to 'click here', new_vocabulary_path %> to add new vocabulary.
        </td>
      </tr>
    <% else %>
      <% @vocabularies.each do |vocabulary| %>
        <tr>
          <td><%= vocabulary.word %></td>
          <td><%= vocabulary.translation %></td>
          <td><%= link_to "Show this vocabulary", vocabulary %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to "New vocabulary", new_vocabulary_path %>

app/views/vocabularies/new.html.erb
<h1>New vocabulary</h1>

<%= render "form", vocabulary: @vocabulary %>

<br>

<div>
  <%= link_to "Back to vocabularies", vocabularies_path %>
</div>

app/views/vocabularies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @vocabulary %>

<div>
  <%= link_to "Edit this vocabulary", edit_vocabulary_path(@vocabulary) %> |
  <%= link_to "Back to vocabularies", vocabularies_path %>

  <%= button_to "Destroy this vocabulary", @vocabulary, method: :delete %>
</div>